title: "亚特兰大现代中文学校 Atlanta Contemporary Chinese Academy (ACCA)"
description: "学习中文 感受中华文化 — Chinese Learning and Culture Community Center"
markdown: kramdown
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "jekyii"
plugins: []
collections: {}
